//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMFSITE.Models
{

    public partial class Banner
    {
        public int ID { get; set; }
        public string Identificador { get; set; }
        public string FileImage { get; set; }
        public string LinkBanner { get; set; }
        public int Prioridad { get; set; }
        public bool Visible { get; set; }
    }
}
