//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMFSITE.Models
{

    public partial class Evento
    {
        public int ID { get; set; }
        public string Titulo { get; set; }
        public string Nombre { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Lugar { get; set; }
        public string Direccion { get; set; }
        public int DisciplinaID { get; set; }
        public string URL { get; set; }
        public bool Visible { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
    }
}
