//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMFSITE.Models
{

    public partial class PlanEtiquetas
    {
        public int ID { get; set; }
        public int PlanID { get; set; }
        public int RespuestaID { get; set; }
    
        public virtual Plan Plan { get; set; }
        public virtual Respuesta Respuesta { get; set; }
    }
}
