//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMFSITE.Models
{

    public partial class PlanDiaEjercicioSeries
    {
        public int ID { get; set; }
        public int PlanDiaEjerciciosID { get; set; }
        public int Secuencia { get; set; }
        public string Repeticiones { get; set; }
        public int Nivel { get; set; }
    
        public virtual PlanDiaEjercicios PlanDiaEjercicios { get; set; }
    }
}
