//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMFSITE.Models
{
    using System.Collections.Generic;
    
    public partial class PlanDias
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanDias()
        {
            this.PlanDiaEjercicios = new HashSet<PlanDiaEjercicios>();
        }
    
        public int ID { get; set; }
        public int PlanID { get; set; }
        public int Dia { get; set; }
        public int RutinaID { get; set; }
        public int DietaID { get; set; }
        public int ProTipID { get; set; }
        public bool Descanso { get; set; }
    
        public virtual Dieta Dieta { get; set; }
        public virtual Plan Plan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlanDiaEjercicios> PlanDiaEjercicios { get; set; }
        public virtual ProTip ProTip { get; set; }
        public virtual Rutina Rutina { get; set; }
    }
}
