//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMFSITE.Models
{
    using System.Collections.Generic;
    
    public partial class RedSocial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RedSocial()
        {
            this.ContenidoEstatico = new HashSet<ContenidoEstatico>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public string Identificador { get; set; }
        public string URL { get; set; }
        public string APPId { get; set; }
        public string APIKey { get; set; }
        public int NoPost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContenidoEstatico> ContenidoEstatico { get; set; }
    }
}
