//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMFSITE.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SlmfDBEntities : DbContext
    {
        public SlmfDBEntities()
            : base("name=SlmfDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accesorio> Accesorio { get; set; }
        public virtual DbSet<Alimento> Alimento { get; set; }
        public virtual DbSet<Banner> Banner { get; set; }
        public virtual DbSet<ContenidoEstatico> ContenidoEstatico { get; set; }
        public virtual DbSet<Cuestionario> Cuestionario { get; set; }
        public virtual DbSet<Dieta> Dieta { get; set; }
        public virtual DbSet<DietaAlimentacion> DietaAlimentacion { get; set; }
        public virtual DbSet<DietaTempos> DietaTempos { get; set; }
        public virtual DbSet<Disciplina> Disciplina { get; set; }
        public virtual DbSet<Ejercicio> Ejercicio { get; set; }
        public virtual DbSet<Elemento> Elemento { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<GrupoMusculos> GrupoMusculos { get; set; }
        public virtual DbSet<Musculo> Musculo { get; set; }
        public virtual DbSet<Nutriente> Nutriente { get; set; }
        public virtual DbSet<Plan> Plan { get; set; }
        public virtual DbSet<PlanDiaEjercicios> PlanDiaEjercicios { get; set; }
        public virtual DbSet<PlanDiaEjercicioSeries> PlanDiaEjercicioSeries { get; set; }
        public virtual DbSet<PlanDias> PlanDias { get; set; }
        public virtual DbSet<PlanEtiquetas> PlanEtiquetas { get; set; }
        public virtual DbSet<Porcion> Porcion { get; set; }
        public virtual DbSet<Posicion> Posicion { get; set; }
        public virtual DbSet<Pregunta> Pregunta { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProTip> ProTip { get; set; }
        public virtual DbSet<RedSocial> RedSocial { get; set; }
        public virtual DbSet<Respuesta> Respuesta { get; set; }
        public virtual DbSet<Rutina> Rutina { get; set; }
        public virtual DbSet<Tempo> Tempo { get; set; }
        public virtual DbSet<UnidadEjercicio> UnidadEjercicio { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
