//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMFAPI.Models
{

    public partial class ContenidoEstatico
    {
        public int ID { get; set; }
        public int RedSocialID { get; set; }
        public string Identificador { get; set; }
    
        public virtual RedSocial RedSocial { get; set; }
    }
}
