//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SLMFAPI.Models
{
    using System;

    public partial class DietaAlimentacion
    {
        public int ID { get; set; }
        public int DietaTemposID { get; set; }
        public string Cantidad { get; set; }
        public Nullable<int> PorcionID { get; set; }
        public int AlimentoID { get; set; }
    
        public virtual Alimento Alimento { get; set; }
        public virtual DietaTempos DietaTempos { get; set; }
        public virtual Porcion Porcion { get; set; }

        public string NombreAlimento 
        {
            get
            {
                string sResponse = "";
                if (!String.IsNullOrEmpty(Cantidad))
                {
                    sResponse = Cantidad.ToString().Trim() + " ";
                }
                if (PorcionID != null)
                {
                    sResponse += Porcion.Abreviacion + " ";
                }
                sResponse += Alimento.Nombre;
                sResponse = sResponse.Trim();
                return sResponse;
            }
        }
    }
}
